CREATE DATABASE  contacto;

USE contacto;

CREATE TABLE IF NOT EXISTS users (
id INT(10)  NOT NULL AUTO_INCREMENT, 
username VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
email VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
comentario VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id),
 UNIQUE KEY users_email_unique (email)

) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;